**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

In [2]:
import numpy as np

arr_a = np.array((11.7, 20, 325, 10.2, 11.7, 20))

arr_a[0] = 5

arr_a

arr_a[arr_a==20]=0
arr_a

print('nbytes', arr_a.nbytes)
print('itemsize',arr_a.itemsize)
arr_a =np.uint8
print(arr_a)
print('itemsize',arr_a.itemsize)

nbytes 48
itemsize 8
<class 'numpy.uint8'>
itemsize <attribute 'itemsize' of 'numpy.generic' objects>


# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

In [26]:
arr_a = np.array([[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]])
print(arr_a)


print('dtype',arr_a.dtype)
print('shape',arr_a.shape)
print('ndim',arr_a.ndim)
print('nsize', arr_a.size)

arr_a[:,-1] *=5
#arr_a[0] /=0
print(arr_a)

arr_a =np.integer



[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. nan]]
dtype float64
shape (3, 3)
ndim 2
nsize 9
[[ 1.  2. 15.]
 [ 4.  5. 30.]
 [ 7.  8. nan]]


# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [36]:
print(np.array([[1,2,3],[4,5,6],[7,8,9]]) * np.array([[10],[10],[10]]))
arr_a=(np.array([[1,2,3],[4,5,6],[7,8,9]]) * np.array([[10],[10],[10]]))
# np.array([[1,2,3],
#           [4,5,6],
#           [7,8,9]]) * 10
display(arr_a[1:3,1:3])
arr_b=(arr_a[1:3,1:3])

arr_b[arr_b==50]=99
print(arr_b)
print(arr_a)



[[10 20 30]
 [40 50 60]
 [70 80 90]]


array([[50, 60],
       [80, 90]])

[[99 60]
 [80 90]]
[[10 20 30]
 [40 99 60]
 [70 80 90]]


# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x4 par 99
4. Réafficher x3

In [46]:
x3= np.array([[1,2,3],
           [4,5,6],
           [7,8,9]]) * 10
x4=(x3[1:,1:])
print(x4)
print('-'*50)
x5=(x3[1:,:2])
print(x5)
print('-'*50)
x4[x4==50]=99
print(x4)
print(x3)


[[50 60]
 [80 90]]
--------------------------------------------------
[[40 50]
 [70 80]]
--------------------------------------------------
[[99 60]
 [80 90]]
[[10 20 30]
 [40 99 60]
 [70 80 90]]


# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

In [12]:
import random

#arr=(8 -2)*np.random.rand(4,4) + 2
arr=np.random.randint(3,8, size=(4,4))
print(arr)

x =np.identity(8)

np.fill_diagonal(x, np.random.randint(0,10, size=8))
print(x)


[[6 4 5 3]
 [4 3 7 3]
 [7 3 6 6]
 [3 6 6 7]]
[[9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


# Exercice 6

- reproduire la matrice suivante (sans les noms de lignes ou colonnes)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

In [32]:
x= np.array([[10,30,5],
           [20,50,1],
           [15,30,np.nan]])
            
print(x)

print(np.nansum(x))
print(np.nansum((x), axis=1))


print(np.nanmean(x, axis=0))

[[10. 30.  5.]
 [20. 50.  1.]
 [15. 30. nan]]
161.0
[45. 71. 45.]
[15.         36.66666667  3.        ]


# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>

In [18]:
x= np.array([[1,4,2],
           [3,5,7],
           [5,4,4]])
y = np.array([20,5,3])

z=x*y
print(z)
print(np.sum(z,axis=1))

[[ 20  20   6]
 [ 60  25  21]
 [100  20  12]]
[ 46 106 132]
